#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate a KiCad symbol and footprint for an I/O pad.

The user instantiates the resulting symbol in the schematic and places
the footprint in the PCB at the desired interposer-edge location.
The footprint carries two properties used by downstream tools:

  IO_CLASS         dispatcher key (wire_bond, flipped_bump, tsv_bump)
  IO_PAD_SIZE_UM   geometric parameter, '<W>x<H>' in micrometers

Outputs:
  <out-dir>/kicad_symbols/<name>.kicad_sym
  <out-dir>/kicad_footprints/<name>.kicad_mod

Currently only wire_bond is implemented; flipped_bump and tsv_bump
are reserved for follow-up work and rejected here.
"""
import argparse
import sys
from pathlib import Path
from typing import Tuple

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_DIR))

from kicad_sym_writer import (  # noqa: E402
    KiCadSymWriter,
    SymbolDefinition,
    SymbolPin,
    PinSide,
    PinType,
)

SUPPORTED_IO_CLASSES = {"wire_bond"}
RESERVED_IO_CLASSES = {"flipped_bump", "tsv_bump"}


def parse_size(size_str: str) -> Tuple[float, float]:
    if "x" in size_str.lower():
        a, b = size_str.lower().split("x", 1)
        return float(a), float(b)
    v = float(size_str)
    return v, v


def io_pad_name(io_class: str, sx_um: float, sy_um: float) -> str:
    cls_camel = "".join(w.capitalize() for w in io_class.split("_"))
    return f"IOPad_{cls_camel}_{sx_um:g}x{sy_um:g}"


def write_symbol(name: str, footprint_ref: str, description: str,
                  out_path: Path) -> None:
    pin = SymbolPin(
        name="1",
        number="1",
        side=PinSide.LEFT,
        pin_type=PinType.PASSIVE,
        position_index=0,
        side_pin_count=1,
    )
    sym = SymbolDefinition(
        name=name,
        pins=[pin],
        body_width=5.08,
        body_height=5.08,
        footprint_ref=footprint_ref,
        description=description,
        reference_prefix="J",
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    KiCadSymWriter().write_symbol_library([sym], str(out_path))


def write_footprint(name: str, io_class: str,
                     sx_um: float, sy_um: float,
                     out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sx_mm = sx_um / 1000.0
    sy_mm = sy_um / 1000.0
    margin_mm = 0.05
    crtyd_l = -sx_mm / 2.0 - margin_mm
    crtyd_r = sx_mm / 2.0 + margin_mm
    crtyd_t = -sy_mm / 2.0 - margin_mm
    crtyd_b = sy_mm / 2.0 + margin_mm
    fab_offset_mm = sy_mm / 2.0 + 0.4
    size_str = f"{sx_um:g}x{sy_um:g}"

    with out_path.open("w") as f:
        f.write(f'(footprint "{name}"\n')
        f.write('  (layer "F.Cu")\n')
        f.write(f'  (descr "I/O pad ({io_class}), {size_str} um. '
                f'Auto-generated by gds_to_kicad/io_pads/generate_io_pad.py")\n')
        f.write('  (attr smd)\n\n')
        f.write(f'  (property "IO_CLASS" "{io_class}")\n')
        f.write(f'  (property "IO_PAD_SIZE_UM" "{size_str}")\n\n')
        f.write('  (fp_text reference "REF**" (at 0 0) (layer "F.SilkS")\n')
        f.write('    (effects (font (size 0.5 0.5) (thickness 0.08)))\n')
        f.write('  )\n')
        f.write(f'  (fp_text value "{name}" (at 0 -{fab_offset_mm:.3f}) (layer "F.Fab")\n')
        f.write('    (effects (font (size 0.4 0.4) (thickness 0.06)))\n')
        f.write('  )\n\n')
        f.write('  (pad "1" smd rect (at 0 0)\n')
        f.write(f'    (size {sx_mm:.6f} {sy_mm:.6f})\n')
        f.write('    (layers "F.Cu" "F.Mask")\n')
        f.write('  )\n\n')
        f.write(f'  (fp_rect (start {crtyd_l:.4f} {crtyd_t:.4f}) '
                f'(end {crtyd_r:.4f} {crtyd_b:.4f})\n')
        f.write('    (stroke (width 0.05) (type solid)) (fill none) (layer "F.CrtYd")\n')
        f.write('  )\n')
        f.write(')\n')


def build_argparser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description="Generate a KiCad symbol+footprint for an external I/O pad.",
    )
    ap.add_argument("--io-class", required=True,
                    choices=sorted(SUPPORTED_IO_CLASSES | RESERVED_IO_CLASSES),
                    help="I/O pad class (drives the IO_CLASS property)")
    ap.add_argument("--size", required=True,
                    help="Pad size in um, '<W>x<H>' or single value '<S>' for square")
    ap.add_argument("--out-dir", default=str(SCRIPT_DIR),
                    help="Output base directory (default: this script's directory)")
    ap.add_argument("--description", default=None,
                    help="Override default symbol description")
    return ap


def main(argv=None) -> int:
    args = build_argparser().parse_args(argv)
    if args.io_class in RESERVED_IO_CLASSES:
        print(f"Error: io-class '{args.io_class}' is reserved for future "
              f"work. Currently only wire_bond is implemented.", file=sys.stderr)
        return 2

    try:
        sx_um, sy_um = parse_size(args.size)
    except ValueError:
        print(f"Error: invalid --size '{args.size}'; expected '<W>x<H>' or "
              f"a single value '<S>' in um.", file=sys.stderr)
        return 2
    if not (sx_um > 0 and sy_um > 0):
        print(f"Error: --size must be positive, got {sx_um:g}x{sy_um:g}.",
              file=sys.stderr)
        return 2
    name = io_pad_name(args.io_class, sx_um, sy_um)
    out_dir = Path(args.out_dir)
    sym_path = out_dir / "kicad_symbols" / f"{name}.kicad_sym"
    fp_path = out_dir / "kicad_footprints" / f"{name}.kicad_mod"
    desc = args.description or (
        f"{args.io_class} I/O pad, {sx_um:g}x{sy_um:g} um "
        "(rendered as TopMetal2 square in the interposer GDS)"
    )

    write_symbol(name, footprint_ref=f"io_pads:{name}",
                  description=desc, out_path=sym_path)
    write_footprint(name, args.io_class, sx_um, sy_um, fp_path)
    print(f"Wrote {sym_path}")
    print(f"Wrote {fp_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
